export const WORKER_CONFIG = {
  pollIntervalMs: 3000,
  uploadDir: process.env.UPLOAD_DIR || './uploads',
  ollamaUrl: process.env.OLLAMA_URL || 'http://localhost:11434',
  ollamaEmbedModel: process.env.OLLAMA_EMBED_MODEL || 'mxbai-embed-large',
  ollamaLlmModel: process.env.OLLAMA_LLM_MODEL || 'llama3',
  ocrServiceUrl: process.env.OCR_SERVICE_URL || 'http://localhost:8100',
  redisUrl: process.env.REDIS_URL,
  embeddingDimensions: 1024,
  workerConcurrency: Number(process.env.WORKER_CONCURRENCY || '2'),
  ocrTimeoutMs: 120_000,
  ollamaTimeoutMs: 60_000,
  llmTextLimit: 3000,
  imageMimeTypes: new Set([
    'image/png',
    'image/jpeg',
    'image/webp',
    'image/tiff',
  ]),
  watchDir: process.env.WATCH_DIR || './watch',
  watchEnabled: process.env.WATCH_ENABLED !== 'false',
  watchStabilityMs: 2000,
  watchDebounceMs: 500,
  watchRescanIntervalMs: 60_000,
  maxFileSizeMB: Number(process.env.MAX_FILE_SIZE_MB || '50'),
} as const
